### PR TITLE
Enable PIC by default

### PR DESCRIPTION
**Pull request by CaledoniaProject**

### CODE REVIEW

**Comment by kubo** [comment]
@CaledoniaProject 
Could you explain use case that PIC must be enabled by default?
If almost users need it, I'll merge this pull request. However I don't think so.
I think it is rare and there is a workaround.

**Comment by CaledoniaProject** [comment]
@kubo I can't use the `.a` library anywhere if `-fPIC` is not enabled.

**Comment by kubo** [comment]
@CaledoniaProject 
`.a` library without PIC is available to make a normal executable.
PIC should be enabled only to make a shared library or a PIE executable.

**Comment by CaledoniaProject** [comment]
I think you misunderstood what PIC does. Here's a common error with your current cmake configuration:

```
/usr/bin/ld: hook/libfunchook.a(funchook.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: hook/libfunchook.a(funchook_x86.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: hook/libfunchook.a(funchook_unix.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: hook/libfunchook.a(disasm_distorm.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
```

**Comment by CaledoniaProject** [comment]
Unless it affects the trampoline code, you should merge it.

**Comment by kubo** [comment]
> I think you misunderstood what PIC does. Here's a common error with your current cmake configuration:

Could you post enough information to reproduce the error? What options do you pass to C compiler?
I guess that you try to link libfunchook.a to create a shared library or a PIE executable.

I can link libfunchook.a with a simple program by the following command line.
```shell
gcc -o prog prog.c -Iinclude -Llib -lfunchook -ldistorm -ldl
```

**Comment by kubo** [comment]
What distribution do you use?
The gcc may enable PIC by default in your distribution.

I'm using Ubuntu 20.04.

**Comment by CaledoniaProject** [comment]
Here's the command line I use on CentOS 7:

```
gcc main.c hook/libfunchook.a hook/libdistorm.a -fPIC -shared -o XX.so
```

**Comment by kubo** [comment]
You try to create a shared library because `-shared` is set.
In the case, PIC must be enabled surely.

**Comment by kubo** [comment]
> Unless it affects the trampoline code, you should merge it.

It doesn't affect it. However I won't.
PIC code has overhead compared with non-PIC code.

If you need PIC-enabled libfunchook.a, add `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` option to cmake command line.

Well, to be honest, the overhead is small when the CPU instruction set was designed for the last few decades.
For example x86 PIC code calls `__i686.get_pc_thunk.??` (`??` is a register name) in many locations but x86_64 doesn't.
See https://stackoverflow.com/questions/6679846/what-is-i686-get-pc-thunk-bx-why-do-we-need-this-call

**Comment by CaledoniaProject** [comment]
OK, whatever you like.

**Pull request closed without merging**
